[build]
  command = "npm run build"
  publish = "."

[forms]
  enabled = false

[build.processing]
  skip_processing = true


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 
